nelmio_api_doc:
    documentation:
        info:
            title: Chekk
            description: API для взаимодействия с приложением
            version: 1.1.0
    areas:
        path_patterns:
            - ^/api(?!/doc(?:\.json)?$)
